### ISSUE TITLE
Error in adding this package to Julia

### ISSUE THREAD

**Issue by MohHizzani** [milankl/Sonums.jl#48]
when trying to add this package to julia 
I got the following error

```
ERROR: Unsatisfiable requirements detected for package Jenks [ea09bcba]:
 Jenks [ea09bcba] log:
 ├─Jenks [ea09bcba] has no known versions!
 └─restricted to versions * by Sonums [df126d66] — no versions left
   └─Sonums [df126d66] log:
     ├─possible versions are: 0.1.0 or uninstalled
     └─Sonums [df126d66] is fixed to version 0.1.0
```

**Comment by milankl** [comment]
Yes, I removed that dependency not completely. Sorry, will do that soon. Current work-around is to simply also install [Jenks](https://github.com/milankl/Jenks.jl), although it's not used for Sonums.jl

**Comment by milankl** [comment]
This should be resolved now in the new master version, @MohHizzani. Let me know if it isn't.

**Comment by milankl** [comment]
For some reasons the builds failed for Julia v1.0, please use 1.1 or 1.2 instead.

**Comment by MohHizzani** [comment]
It works now!

**Comment by milankl** [comment]
Let me know of any other issues that you run into.
